namespace Tests
{
	public enum ArgType
	{
		NULL
		,NOTNULL
		,EMPTY
		//Language Only
		,LANGUAGE_ONLY
		,LANGUAGE_ONLY_UPPERCASE
		,LANGUAGE_ONLY_LOWERCASE
		,LANGUAGE_ONLY_MIXEDCASE
		//FirstName with language
		,FIRSTNAME_WITH_LANGUAGE
		,FIRSTNAME_WITH_UPPERCASELANGUAGE
		,FIRSTNAME_WITH_LOWERCASELANGUAGE
		,FIRSTNAME_WITH_MIXEDCASELANGUAGE
		//Swap FirstName with language
		,SWAP_FIRSTNAME_WITH_LANGUAGE
		,SWAP_FIRSTNAME_WITH_UPPERCASELANGUAGE
		,SWAP_FIRSTNAME_WITH_LOWERCASELANGUAGE
		,SWAP_FIRSTNAME_WITH_MIXEDCASELANGUAGE
		//FirstName with third Parameter
		,FIRSTNAME_LANGUAGE_AND_THIRD_PARAMETER
		,FIRSTNAME_UPPER_LANGUAGE_AND_THIRD_PARAMETER
		,FIRSTNAME_LOWER_LANGUAGE_AND_THIRD_PARAMETER
		,FIRSTNAME_MIXED_LANGUAGE_AND_THIRD_PARAMETER
		//Swap FirstName with third Parameter
		,SWAP_FIRSTNAME_LANGUAGE_AND_THIRD_PARAMETER
		,SWAP_FIRSTNAME_UPPER_LANGUAGE_AND_THIRD_PARAMETER
		,SWAP_FIRSTNAME_LOWER_LANGUAGE_AND_THIRD_PARAMETER
		,SWAP_FIRSTNAME_MIXED_LANGUAGE_AND_THIRD_PARAMETER
		//FullName with Language
		,FULLNAME_WITH_LANGUAGE
		,FULLNAME_WITH_UPPERCASELANGUAGE
		,FULLNAME_WITH_LOWERCASELANGUAGE
		,FULLNAME_WITH_MIXEDCASELANGUAGE
		//swap FullName with language
		,SWAP_FULLNAME_WITH_LANGUAGE
		,SWAP_FULLNAME_WITH_UPPERCASELANGUAGE
		,SWAP_FULLNAME_WITH_LOWERCASELANGUAGE
		,SWAP_FULLNAME_WITH_MIXEDCASELANGUAGE
		//FullName with Third Parameter
		,FULLNAME_LANGUAGE_AND_THIRD_PARAMETER
		,FULLNAME_UPPER_LANGUAGE_AND_THIRD_PARAMETER
		,FULLNAME_LOWER_LANGUAGE_AND_THIRD_PARAMETER
		,FULLNAME_MIXED_LANGUAGE_AND_THIRD_PARAMETER
		//Swap FullName with Third Parameter
		,SWAP_FULLNAME_LANGUAGE_AND_THIRD_PARAMETER
		,SWAP_FULLNAME_UPPER_LANGUAGE_AND_THIRD_PARAMETER
		,SWAP_FULLNAME_LOWER_LANGUAGE_AND_THIRD_PARAMETER
		,SWAP_FULLNAME_MIXED_LANGUAGE_AND_THIRD_PARAMETER
	}

	public enum LanguageCase
	{
		NORMAL
		,UPPER 
		,LOWER 
		,MIXED
	}

	public enum Name
	{
		NONAME
		,FIRSTNAME
		,FULLNAME
	}

	public enum ThirdParameter
	{
		YES
		,NO
	}

	public enum SwapNameWithLanguage
	{
		YES
		,NO
	}
}